# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Maëlle Salmon
tagline:          'A Jekyll theme'
description:      'A statistician currently trying to build her webpage with Jekyll.'
url:              http://masalmon.github.io
baseurl:          /

author:
  name:           'Maëlle Salmon'
  url:            https://twitter.com/masalmon

paginate:         5

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist

github:
  repo:           https://github.com/masalmon
