# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Maëlle
tagline:          'Not a fish'
description:      ''
url:              http://masalmon.github.io
baseurl:          /

author:
  name:           'Maëlle Salmon'
  url:            https://twitter.com/masalmon

paginate:         5

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist

github:
  repo:           https://github.com/masalmon
